### ISSUE TITLE
Custom port instead of 8080

### ISSUE THREAD

**Issue by kpx-dev** [ICTO/ansible-jenkins#13]
Hi can we refactor to use custom port instead of default 8080. 

Thanks.

**Comment by sumdog** [comment]
I've got this working in my fork. There's a pull request for this as well. 

https://github.com/sumdog/ansible-jenkins

**Comment by aehlke** [comment]
The docs show specifying port 8081 so I assume it has support now, or the docs are misleading?

**Comment by kpx-dev** [comment]
@aehlke looks like @sumdog got the PR merged, yey thanks!

**Comment by hlassiege** [comment]
Hi,

There is maybe a problem. 
The configuration is the last step of the playbook. 
Jenkins starts for the first time on port 8080 and everything in cli.yml expects jenkins to run on port 8080. 
If another process use the port 8080, every operations in cli.yml will fail and config.yml will never be executed.

Am I wrong ?

**Comment by aehlke** [comment]
@hlassiege good point. I'd open a new issue for that bug.

**Comment by hlassiege** [comment]
I've tried to fix it for my needs here : https://github.com/hopwork/ansible-jenkins

It works but feel free to tell me if it follows best practices or not.

**Comment by aehlke** [comment]
Would be easiest to review if you could submit the change as a PR
