### ISSUE TITLE
Release on galaxy?

### ISSUE THREAD

**Issue by gforcada** [ICTO/ansible-jenkins#25]
Hi,

I was trying to set up a requirements.txt file for ansible roles and found that I either suck at searching or this role is not uploaded on galaxy.ansible.com. Is there any reason not to do so? If not, could someone register it there?

Thanks in advance!

**Comment by riltsken** [comment]
+1 to this. I attempted to add to ansible galaxy myself but it requires the Readme to be renamed to README https://github.com/ICTO/ansible-jenkins/pull/26

**Comment by gforcada** [comment]
ping, anyone willing to make that happen?

**Comment by kristofkeppens** [comment]
This role is now available on ansible galaxy, closing this issue

https://galaxy.ansible.com/list#/roles/4269

**Comment by gforcada** [comment]
Many thanks!!
