### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by gforcada** [ICTO/ansible-jenkins#28]
Hi, thanks @flyapen for releasing on ansible galaxy, unfortunately the release you pushed there is quite old (commit b311158), could you make a new tag targeting current development branch?

**Comment by kristofkeppens** [comment]
@gforcada my mistake, I created a new release from the current state of the development branch. We will try to keep the releases up to date with the bugfixes / features .

**Comment by gforcada** [comment]
Thanks!
