### ISSUE TITLE
This role is only Debian compatible

### ISSUE THREAD

**Issue by fiunchinho** [ICTO/ansible-jenkins#48]
When running this role

```
fatal: [192.168.33.10]: FAILED! => {"changed": false, "cmd": "apt-get update", "failed": true, "msg": "[Errno 2] No such file or directory", "rc": 2}
```

on CentOS 6 and `ansible 2.1.0.0`

**Comment by tberton** [comment]
Could you post more output from this role?

It's hard to identify where this error is coming from without more information. 

I cannot see any references to apt-related commands in non-Debian sections in this role.

**Comment by fiunchinho** [comment]
Looks like the ansible-galaxy version of this role is outdated https://galaxy.ansible.com/detail#/role/4269. It installs and older debian specific version.
