### ISSUE TITLE
[DEPRECATION WARNING]: Using bare variables is deprecated

### ISSUE THREAD

**Issue by lmilbaum** [ICTO/ansible-jenkins#50]
TASK [flyapen.jenkins : Install dependencies] **********************************
[DEPRECATION WARNING]: Using bare variables is deprecated. Update your 
playbooks so that the environment value uses the full variable syntax 
('{{jenkins.deb.dependencies}}').
This feature will be removed in a future 
release. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.

**Comment by takluyver** [comment]
I've made #54 to fix this.
