### ISSUE TITLE
What is a license for this playbook?

### ISSUE THREAD

**Issue by drakmail** [ICTO/ansible-jenkins#6]
Please add such information. I want to use it for some of my projects. Thanks!

**Comment by tberton** [comment]
Hi @drakmail ,
I'll add a Creative Commons Attribution-ShareAlike 4.0 International license (http://creativecommons.org/licenses/by-sa/4.0/) as soon as possible.

Feel free to comment on this if you think another license is more approriate.

**Comment by drakmail** [comment]
Thank you, CC SA is are great choice!

**Comment by fawkesley** [comment]
Closed by https://github.com/ICTO/ansible-jenkins/pull/10 - thanks :)

**Comment by aehlke** [comment]
MIT license is ideal, thank you

**Comment by gforcada** [comment]
Shouldn't this be closed as #10 got merged? :)
