### ISSUE TITLE
Error when deploying 

### ISSUE THREAD

**Issue by sunshine69** [ICTO/ansible-jenkins#60]
Run on ubuntu xenial - 

TASK [flyapen.jenkins : Install/update plugins] ********************************
task path: /mnt/mmcblk0p1/tmp/work/xvt-dpe-cloud-infrastructure-stream2/roles/flyapen.jenkins/tasks/plugins.yml:7
failed: [13.54.197.74] (item=plugins) => {"changed": true, "cmd": "java -jar /opt/jenkins/jenkins-cli.jar -s http://localhost:8081 install-plugin plugins", "delta": "0:00:00.690971", "end": "2017-01-14 11:07:45.015734", "failed": true, "item": "plugins", "rc": 6, "start": "2017-01-14 11:07:44.324763", "stderr": "\nERROR: anonymous is missing the Overall/Read permission", "stdout": "", "stdout_lines": [], "warnings": []}

**Comment by mpodber1971** [comment]
see https://github.com/ICTO/ansible-jenkins/issues/61
